_:
  location: EU
  organizationId: redkubes
  project: otomi-cloud
  region: europe-west4

bq:
  location: EU
  metering-set: otomi_metering

dns:
  name: otomi.cloud
  zone: otomi-dns
  accountName: otomi-dns-manager
  
gke:
  release-channel: stable
  addons: HorizontalPodAutoscaling,HttpLoadBalancing
  disk-size: 100
  disk-type: pd-standard
  enable-autoprovisioning: true
  enable-autorepair: true
  enable-autoscaling: true
  enable-autoupgrade: true
  enable-ip-alias: true
  enable-network-egress-metering: true
  enable-network-policy: true
  enable-resource-consumption-metering: true
  enable-tpu: true
  image-type: COS
  # labels: 'some=label,another=bla'
  machine-type: n1-standard-4
  maintenance-window: 01:00
  max-cpu: 8
  max-memory: 32
  max-nodes: 7
  metadata: disable-legacy-endpoints=true
  min-cpu: 4
  min-memory: 8
  min-nodes: 1
  node-labels: 'customer=otomi'
  num-nodes: 3
  # enable-pod-security-policy: true
