_:
  region: westeurope
  subscriptionId: null
  tenantId: null
  zones: 1 2 3
acr:
  enabled: true
  name: acrname
  resource-group: rg-otomi
  role: acrpull
ad:
  enabled: true
aks:
  create:
    auto-upgrade-channel: stable
    dns-service-ip: 10.2.0.10
    enable-cluster-autoscaler: true
    network-plugin: azure
    network-policy: calico
    nodepool-name: agentpool1
  nodePoolDefaults:
    max-count: 6
    max-pods: 42
    min-count: 3
    node-os-disk-size-gb: 200
    node-vm-size: Standard_D3_v2
appgw:
  enabled: false
  sslPolicy:
    name: AppGwSslPolicy20170401S
    policy-type: Predefined
  update:
    capacity: 2
    sku: WAF_v2
  waf:
    disabled-rule-groups: []
    enabled: true
    exclusions: []
    file-upload-limit-in-mb: 750
    firewall-mode: Detection
    max-request-body-size-in-kb: 128
    request-body-check: true
    rule-set-type: OWASP
    rule-set-version: '3.1'
dns:
  name: otomi-cloud
  resourceGroup: otomi-dns
  zone: aks.otomi.cloud
kms:
  enabled: true
  resourceGroup: otomi-vault
  vault: otomi-vault
preview:
  enabled: false
vnet:
  appgw-subnet-cidr: 10.1.0.0/16
