_:
  region: westeurope
  subscriptionId: null
  tenantId: null
  zones: 1 2 3
acr:
  enabled: true
  name: acrname
  # resourceGroup: rg-otomi
  role: acrpull
ad:
  enabled: true
aks:
  create:
    enable-managed-identity: true
    # auto-upgrade-channel: stable
    dns-service-ip: 10.2.0.10
    service-cidr: 10.2.0.0/24
    enable-cluster-autoscaler: true
    network-plugin: azure
    network-policy: calico
    nodepool-name: agentpool1
  nodePoolDefaults:
    max-count: 6
    max-pods: 42
    min-count: 3
    node-osdisk-size: 200
    node-vm-size: Standard_D3_v2
appgw:
  enabled: false
  sslPolicy:
    name: AppGwSslPolicy20170401S
    policy-type: Predefined
  update:
    capacity: 2
    sku: WAF_v2
  waf:
    disabled-rule-groups: []
    enabled: true
    exclusions: []
    file-upload-limit-in-mb: 750
    firewall-mode: Detection
    max-request-body-size-in-kb: 128
    request-body-check: true
    rule-set-type: OWASP
    rule-set-version: '3.1'
dns:
  name: otomi-cloud
  resourceGroup: otomi-dns
  zone: aks.otomi.cloud
kms:
  enabled: true
  resourceGroup: otomi-vault
  vault: otomi-vault
preview:
  enabled: false
storage:
  enabled: true
  create:
    sku: Standard_LRS
  privateEndpoint:
    enabled: true
  containers:
    enabled: true
    names: harbor loki
vnet:
  subnet:
    id: '/subscriptions/xx/resourceGroups/xx/providers/Microsoft.Network/virtualNetworks/xx/subnets/xx'
