_:
  # resourceGroup: rg-otomi-dev
  zones: '1'

aks:
  create:
    kubernetes-version: 1.19.7
    auto-upgrade-channel: patch
  nodePoolDefaults:
    min-count: 1
    max-count: 7
  additionalNodePools:
  # - name: agentpool2

db:
  postgres:
    enabled: true
    names: otomi-dta
    otomi-dta-utrecht:
      create:
        # public-network-access: Disabled
        location: westeurope
        admin-user: pgadmin
        admin-password: xxx
        sku-name: GP_Gen5_4
        version: 11
      ipAccess:
        - 123.123.123.123

preview:
  enabled: true
