_:
  environment: dev
  zones: '1'

aks:
  create:
    kubernetes-version: 1.19.3
    auto-upgrade-channel: patch
  nodePoolDefaults:
    min-count: 1
    max-count: 7
  additionalNodePools:
  # - name: agentpool2
